### ISSUE TITLE
User Story 1: List of all Locations

### ISSUE THREAD

**Issue by AlexDernov** [AlexDernov/capstone-project-hungry-oar#1]
## Value Proposition

**As a** hungry kayaker
**I want** to see a list of cafes and restaurants by the water in Hamburg
**so that** I can decide where I can eat and drink without leaving the boat.
​

## Description

![Unbenannt-2023-06-30-1011](https://github.com/AlexDernov/Hungry-Oar-App/assets/127208943/7a6bf571-b8d7-4e02-9f22-a09d0cfa3133)
​

## Acceptance Criteria

- [ ]  All locations are displayed as a list 🖼️ 
- [ ]  Listitem has the same height as content 
- [ ]  Each locations's image is displayed 🖼️ 
- [ ]  Each locations's title is displayed 🖼️ 
- [ ]  Each locations's address is displayed 🖼️   ​

## Tasks

- [ ]  Open  new branch
- [ ]  Create db/models/Location
- [ ]  Create db/connect
- [ ]  Create a handler function with "if (request.method === "GET")"
- [ ]  Fetch all locations data from MongoDB Atlas using SWR State, so that location are available on all previous pages
- [ ]  Create the page pages/locations/index that renders the LocationsList component
- [ ]  Create the component LocationsList to render a list.​

## Complexity

M

**Comment by NicoleHoerner** [comment]
It is an awesome idea in general! And a good start for US1😀

**Comment by AlexDernov** [comment]
Thank you! I wish you a good start too!
